### ISSUE TITLE
option file : how to enable link to the code ?

### ISSUE THREAD

**Issue by yboujraf** [mipatterson/typedoc-plugin-pages#18]
Dear @mipatterson 

### OPTION FILE

Which is the option to enable link with the code ? From my side I can see only the path but not as a link?

![image](https://user-images.githubusercontent.com/6151258/82628265-af11fc00-9bec-11ea-8f03-368f7a5f55da.png)

Best Regards,
Youssef

**Comment by mipatterson** [comment]
I think this question would be better posed to the authors of TypeDoc, as this is a feature of the TypeDoc library. That being said, I _think_ that the TypeDoc library will make this text a hyperlink when there is a git remote detected.
