### ISSUE TITLE
Finish custom theme docs?

### ISSUE THREAD

**Issue by tanepiper** [mipatterson/typedoc-plugin-pages#31]
I'm looking to use the theme `typedoc-theme-neo` with my docs and would like to include changelogs as pages using this plugin.

Currently the docs only support the pages theme, and the documentation for custom themes is not finished https://github.com/mipatterson/typedoc-plugin-pages/blob/develop/docs-source/themes/custom-themes.md

Attempted to integrate the two, but it breaks output and does not generate docs.

**Comment by loopingz** [comment]
You can look at that one: https://github.com/mipatterson/typedoc-plugin-pages/pull/32

I started a `typedoc-loopingz-theme` based on `typedoc-neo-theme` that have this available but include also some redesign: https://cluster.static.loopingz.com/webda.io-docs/index.html if you want to see a demo

If it can help you

**Comment by tanepiper** [comment]
@loopingz Hey, I've tried it out and so far looks great but I've had issues getting the pages working to look like yours, I assume some custom styling? I see you haven't released it though?

**Comment by loopingz** [comment]
I did release: [npm](https://www.npmjs.com/package/typedoc-loopingz-theme)
I'm still going under heavy development as I will probably add some custom plugin to add UML diagram and a few more things
I did a PR to get the title from .md directly: https://github.com/mipatterson/typedoc-plugin-pages/pull/33 and plan to add a few more customizations.
I might have to do a full fork if the current maintainer is busy as I would like to move forward quickly.

Do not hesitate to contact me if you have issue, or even create issue in the theme repository: https://github.com/loopingz/typedoc-loopingz-theme

**Comment by tanepiper** [comment]
@loopingz Great thanks, I'll probably have some tickets but will also see what I can PR

**Comment by mipatterson** [comment]
@tanepiper I'm currently finishing up validating the latest TypeDoc releases against this plugin. (I've got a couple of flaky UI tests to work though.) Once that is done I was planning on publishing a new release. I'll take a look at @loopingz's PR and see if I can get some documentation around custom theme's in place as a part of that release.
